config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: {
      sessions: 'admin/sessions',
      passwords: 'admin/passwords'
  }
  devise_for :users, path: 'user', controllers: { sessions: 'user/sessions',
                                                            passwords: 'user/passwords',
                                                            registrations: 'user/registrations'
                                                          }
  namespace :user, url: '/' do
    get '/search', to: 'search_email#index'
    get '/welcome', to: 'search_email#welcome_email'
    get '/searching_history', to: 'history_search_emails#index'
    get '/download-file', to: 'search_email#download'
    resources :email_campaigns, only: [:new, :create, :show, :index ]
    root to: 'search_email#index'
  end
  namespace :admin, url: '/admin' do
    resources :user, only: [:index, :destroy, :update]
    get '/edit_profile', to: "admin#edit_profile"
    post '/edit_profile', to: "admin#update_info"
    root to: 'user#index'
  end
  root to: 'user/search_email#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/email_campaign.rb
class EmailCampaign < ApplicationRecord
  has_many :messages, class_name: "Ahoy::Message" , :foreign_key => :campaign_id
  belongs_to :user


  mount_uploader :file, EmailFileUploader

  def read_csv
    array = []
    CSV.foreach("#{Rails.public_path}/#{self.file.url}" , headers: false).each_with_index do |row, index|
      next if index == 0
      is_real = EmailValidator.valid?(row[1])
      array << row[1] if is_real
    end
    update(list_email: array)
    array
  end
end

app/controllers/email_campaigns_controller.rb
class EmailCampaignsController < ApplicationController

  def index
    @email_campaigns = EmailCampaign.where(user_id: current_user.id)
  end

  def show
    @email_campaign = EmailCampaign.find(params[:id])
    @max_number = JSON.parse(@email_campaign.list_email).length || 100
    @open_count = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").group_by_day(:opened_at, range: 2.weeks.ago..(Time.now + 2.weeks))
    @percent_complete = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").count * 100/@max_number
  end

  def new
    @email_campaign = EmailCampaign.new
  end

  def create
    start_time = params[:start_time]
    end_time = params[:end_time]
    @start_time = Time.new start_time["date(1i)"].to_i, start_time["date(2i)"].to_i, start_time["date(3i)"].to_i, start_time["date(4i)"].to_i, start_time["date(5i)"].to_i
    @end_time = Time.new end_time["date(1i)"].to_i, end_time["date(2i)"].to_i, end_time["date(3i)"].to_i, end_time["date(4i)"].to_i, end_time["date(5i)"].to_i
    @email_campaign = EmailCampaign.new(start_time: @start_time, end_time: @end_time, user_id: current_user.id, file: params[:file_data])
    if @email_campaign.save!
      array = @email_campaign.read_csv
      if Rails.env = "production"
        EmailCampaignJob.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      end
      if Rails.env = "development"
        EmailCampaignWorker.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      end
      redirect_to email_campaigns_path
    else
      render 'new'
    end
  end

  private

  def send_email_params
    params.permit(:from, :content, :subject, start_time: [], end_time: [], file_data: [])
  end

end

app/controllers/user/email_campaigns_controller.rb
class User::EmailCampaignsController < User::BaseController

  def index
    @email_campaigns = EmailCampaign.where(user_id: current_user.id).paginate(:page => params[:page] || 1, :per_page => 10)
  end

  def show
    @email_campaign = EmailCampaign.find(params[:id])
    @max_number = JSON.parse(@email_campaign.list_email).length || 100
    @open_count = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").group_by_day(:opened_at, range: @email_campaign.start_time.yesterday..@email_campaign.end_time)
    @percent_complete = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").count * 100/@max_number
    @list_email_campaign = @email_campaign.messages.paginate(:page => params[:page] || 1, :per_page => 10)
  end

  def new
    @email_campaign = EmailCampaign.new
  end

  def create
    start_time = params[:start_time]
    end_time = params[:end_time]
    @start_time = Time.new start_time["date(1i)"].to_i, start_time["date(2i)"].to_i, start_time["date(3i)"].to_i, start_time["date(4i)"].to_i, start_time["date(5i)"].to_i
    @end_time = Time.new end_time["date(1i)"].to_i, end_time["date(2i)"].to_i, end_time["date(3i)"].to_i, end_time["date(4i)"].to_i, end_time["date(5i)"].to_i
    @email_campaign = EmailCampaign.new(start_time: @start_time, end_time: @end_time, user_id: current_user.id, file: params[:file_data])
    if @email_campaign.save!
      array = @email_campaign.read_csv
      # if Rails.env == "production"
        EmailCampaignJob.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      # end
      # if Rails.env == "development"
      #   EmailCampaignWorker.perform_in(@start_time,array, params[:from], params[:subject], params[:content], @email_campaign.id)
      # end
      redirect_to user_email_campaigns_path
    else
      render 'new'
    end
  end

  private

  def send_email_params
    params.permit(:from, :content, :subject, start_time: [], end_time: [], file_data: [])
  end

end

app/views/email_campaigns/index.html.erb
<div class="container-fluid">
  <div class="row">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Start Time</th>
        <th class="text-center">End Time</th>
        <th class="text-center">Number of Sent Email</th>
      </tr>
      </thead>
      <tbody>
      <% unless @email_campaigns.nil? %>
          <% @email_campaigns.each_with_index do |email_campaign, index| %>
              <tr>
                <td class="text-center"><%= index + 1 %></td>
                <td class="text-center"><%= email_campaign.start_time %></td>
                <td class="text-center"><%= email_campaign.end_time %></td>
                <td class="text-center">
                  <% unless email_campaign.list_email.nil? %>
                    <%= JSON.parse(email_campaign.list_email).length %>
                  <% else %>
                    0
                  <% end %>
                </td>
                <td><a href="<%= email_campaign_path(email_campaign) %>">Show</a></td>
              </tr>
          <% end %>
      <% else %>
          <tr><p>No result found</p></tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/email_campaigns/new.html.erb
<div class="container-fluid">
  <h1>Email Content</h1>
  <div class="row">
    <div class = "well">
      <%= form_tag(email_campaigns_path, method: "post", multipart: true) do %>
          <div class="form-group">
            <%= label_tag :start_time %>
            <%= datetime_select :start_time, :date , prefix: :start_time, :order => [:month, :day, :year,:hour,:minute], class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :end_time %>
            <%= datetime_select :end_time, :date, :order => [:month, :day, :year,:hour,:minute], class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :from %>
            <%= text_field_tag :from, nil, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag :to %>
            <%= file_field_tag :file_data, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :subject %>
            <%= text_field_tag :subject,  nil, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag :content %>
            <%= text_area_tag :content, nil, class: 'ckeditor form-control' %>
            <!--<input id="x" value="Editor content goes here" type="hidden" name="content">-->
            <!--<trix-editor input="x" style="min-height: 20em"></trix-editor>-->
          </div>
          <div class="form-group">
          </div>
          <%= submit_tag "Send", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>