config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: {
      sessions: 'admin/sessions',
      passwords: 'admin/passwords'
  }
  devise_for :users, path: 'user', controllers: { sessions: 'user/sessions',
                                                            passwords: 'user/passwords',
                                                            registrations: 'user/registrations'
                                                          }
  namespace :user, url: '/' do
    get '/search', to: 'search_email#index'
    get '/welcome', to: 'search_email#welcome_email'
    get '/searching_history', to: 'history_search_emails#index'
    get '/download-file', to: 'search_email#download'
    resources :email_campaigns, only: [:new, :create, :show, :index ]
    root to: 'search_email#index'
  end
  namespace :admin, url: '/admin' do
    resources :user, only: [:index, :destroy, :update]
    get '/edit_profile', to: "admin#edit_profile"
    post '/edit_profile', to: "admin#update_info"
    root to: 'user#index'
  end
  root to: 'user/search_email#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/email_campaign.rb
class EmailCampaign < ApplicationRecord
  has_many :messages, class_name: "Ahoy::Message" , :foreign_key => :campaign_id
  belongs_to :user


  mount_uploader :file, EmailFileUploader

  def read_csv
    array = []
    CSV.foreach("#{Rails.public_path}/#{self.file.url}" , headers: false).each_with_index do |row, index|
      next if index == 0
      is_real = EmailValidator.valid?(row[1])
      array << row[1] if is_real
    end
    update(list_email: array)
    array
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :email_campaigns
  has_many :history_search_emails
  has_many :messages, class_name: "Ahoy::Message"

  %w(first_name last_name).each do |i|
    validates_presence_of i
  end
end

app/controllers/admin/user_controller.rb
class Admin::UserController < Admin::BaseController
  before_action :admin_set_user, only: [:delete, :update]

  def index
    @users = User.all
  end
  def destroy
    @user.delete
    redirect_to admin_index_path
  end
  def update
    is_lock = @user.is_lock
    @user.update(is_lock: !is_lock)
    redirect_to admin_index_path
  end

  def edit
    @admin = current_admin
  end

  private

  def admin_set_user
    @user = User.find(params[:id])
  end
end

app/controllers/email_campaigns_controller.rb
class EmailCampaignsController < ApplicationController

  def index
    @email_campaigns = EmailCampaign.where(user_id: current_user.id)
  end

  def show
    @email_campaign = EmailCampaign.find(params[:id])
    @max_number = JSON.parse(@email_campaign.list_email).length || 100
    @open_count = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").group_by_day(:opened_at, range: 2.weeks.ago..(Time.now + 2.weeks))
    @percent_complete = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").count * 100/@max_number
  end

  def new
    @email_campaign = EmailCampaign.new
  end

  def create
    start_time = params[:start_time]
    end_time = params[:end_time]
    @start_time = Time.new start_time["date(1i)"].to_i, start_time["date(2i)"].to_i, start_time["date(3i)"].to_i, start_time["date(4i)"].to_i, start_time["date(5i)"].to_i
    @end_time = Time.new end_time["date(1i)"].to_i, end_time["date(2i)"].to_i, end_time["date(3i)"].to_i, end_time["date(4i)"].to_i, end_time["date(5i)"].to_i
    @email_campaign = EmailCampaign.new(start_time: @start_time, end_time: @end_time, user_id: current_user.id, file: params[:file_data])
    if @email_campaign.save!
      array = @email_campaign.read_csv
      if Rails.env = "production"
        EmailCampaignJob.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      end
      if Rails.env = "development"
        EmailCampaignWorker.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      end
      redirect_to email_campaigns_path
    else
      render 'new'
    end
  end

  private

  def send_email_params
    params.permit(:from, :content, :subject, start_time: [], end_time: [], file_data: [])
  end

end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user
  layout 'application_user'

  private

  def check_user
    if !current_user.nil? && current_user.is_lock && current_user.class.to_s == "User"
      sign_out current_user
      render 'layouts/lock'
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  layout 'application_user'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/email_campaigns_controller.rb
class User::EmailCampaignsController < User::BaseController

  def index
    @email_campaigns = EmailCampaign.where(user_id: current_user.id).paginate(:page => params[:page] || 1, :per_page => 10)
  end

  def show
    @email_campaign = EmailCampaign.find(params[:id])
    @max_number = JSON.parse(@email_campaign.list_email).length || 100
    @open_count = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").group_by_day(:opened_at, range: @email_campaign.start_time.yesterday..@email_campaign.end_time)
    @percent_complete = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").count * 100/@max_number
    @list_email_campaign = @email_campaign.messages.paginate(:page => params[:page] || 1, :per_page => 10)
  end

  def new
    @email_campaign = EmailCampaign.new
  end

  def create
    start_time = params[:start_time]
    end_time = params[:end_time]
    @start_time = Time.new start_time["date(1i)"].to_i, start_time["date(2i)"].to_i, start_time["date(3i)"].to_i, start_time["date(4i)"].to_i, start_time["date(5i)"].to_i
    @end_time = Time.new end_time["date(1i)"].to_i, end_time["date(2i)"].to_i, end_time["date(3i)"].to_i, end_time["date(4i)"].to_i, end_time["date(5i)"].to_i
    @email_campaign = EmailCampaign.new(start_time: @start_time, end_time: @end_time, user_id: current_user.id, file: params[:file_data])
    if @email_campaign.save!
      array = @email_campaign.read_csv
      # if Rails.env == "production"
        EmailCampaignJob.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      # end
      # if Rails.env == "development"
      #   EmailCampaignWorker.perform_in(@start_time,array, params[:from], params[:subject], params[:content], @email_campaign.id)
      # end
      redirect_to user_email_campaigns_path
    else
      render 'new'
    end
  end

  private

  def send_email_params
    params.permit(:from, :content, :subject, start_time: [], end_time: [], file_data: [])
  end

end

app/controllers/user/history_search_emails_controller.rb
class User::HistorySearchEmailsController < User::BaseController
  def index
    @history_search_results = HistorySearchEmail.where(user_id: current_user.id).paginate(:page => params[:page] || 1, :per_page => 10)
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  layout 'application_user'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  layout 'application_user'

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :phone, :address, :birthday, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/user/search_email_controller.rb
class User::SearchEmailController < User::BaseController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    if params[:email]
      @search = true
      begin
        if EmailValidator.valid?(email_params)
          is_real = EmailVerifier.check(email_params)
          @email_live = is_real ? 1 : 0
        else
          @email_live = 0
        end
      rescue Exception
        @email_live = 0
      end
    else
      @search = false
    end
    respond_to do |format|
      format.html
      format.json do
        return render json: {email_is_exist: @email_live },head: 200 if @search
        render json:{email_is_exist: 0},head: 200 if !@search
      end
    end
  end

  def download
    if current_user
      send_file "#{Rails.public_path}/ACE_EmailHarvest_Install.zip", type: 'application/zip', disposition: 'inline'
    end
  end
  private

  def email_params
    params.require(:email)
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  layout 'application_user'

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/user/email_campaigns/index.html.erb
<div class="container-fluid">
  <div class="row">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Start Time</th>
        <th class="text-center">End Time</th>
        <th class="text-center">Number of Sent Email</th>
      </tr>
      </thead>
      <tbody>
      <% unless @email_campaigns.nil? %>
          <% @email_campaigns.each_with_index do |email_campaign, index| %>
              <tr>
                <td class="text-center"><%= index + 1 %></td>
                <td class="text-center"><%= email_campaign.start_time %></td>
                <td class="text-center"><%= email_campaign.end_time %></td>
                <td class="text-center">
                  <% unless email_campaign.list_email.nil? %>
                    <%= JSON.parse(email_campaign.list_email).length %>
                  <% else %>
                    0
                  <% end %>
                </td>
                <td><a href="<%= user_email_campaign_path(email_campaign) %>">Show</a></td>
              </tr>
          <% end %>
      <% else %>
          <tr><p>No result found</p></tr>
      <% end %>
      </tbody>
    </table>
    <div align="center"><%= will_paginate @email_campaigns, renderer: BootstrapPagination::Rails %></div>
  </div>
</div>

app/views/user/email_campaigns/new.html.erb
<% if @email_campaign.errors.any? %>
    <div class="alert alert-danger alert-block devise-bs">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <% @email_campaign.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </div>
<% end %>
<div class="container-fluid">
  <h1>Email Content</h1>
  <div class="row">
    <div class = "well">
      <%= form_tag(user_email_campaigns_path, method: "post", multipart: true, local: true) do %>
          <div class="form-group">
            <%= label_tag :start_time %>
            <%= datetime_select :start_time, :date , default: Time.zone.now , prefix: :start_time, :order => [:month, :day, :year,:hour,:minute], class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :end_time %>
            <%= datetime_select :end_time, :date, default: DateTime.now, prefix: :end_time, :order => [:month, :day, :year,:hour,:minute], class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :from %>
            <%= text_field_tag :from, nil, :required => true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag :to %>
            <%= file_field_tag :file_data, :required => true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :subject %>
            <%= text_field_tag :subject,  nil, :required => true,  class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag :content %>
            <%= text_area_tag :content, nil, class: 'ckeditor form-control' %>
            <!--<input id="x" value="Editor content goes here" type="hidden" name="content">-->
            <!--<trix-editor input="x" style="min-height: 20em"></trix-editor>-->
          </div>
          <div class="form-group">
          </div>
          <%= submit_tag "Send", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/email_campaigns/show.html.erb
<div class="container-fluid">
  <div class="row">
    <%= line_chart @open_count.count, min: 0, max: @max_number , xtitle: "Date", ytitle: "Number Of Opened Mail" %>
  </div>
  <div class="row">
    <h3>Progress:</h3>
    <div class="progress">
      <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<%= @percent_complete %>"
           aria-valuemin="0" aria-valuemax="100" style="width: <%= @percent_complete %>%">
        <%= @percent_complete %>% Complete
      </div>
    </div>
  </div>
  <div class="clear-fix"></div>
  <div class="row">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Email</th>
        <th class="text-center">Opened At</th>
      </tr>
      </thead>
      <tbody>
        <% @list_email_campaign.each_with_index do |email_campaign, index| %>
            <tr>
              <td class="text-center"><%= index + 1 %></td>
              <td class="text-center"><%= email_campaign.to %></td>
              <td class="text-center"><%= email_campaign.opened_at %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
    <div align="center"><%= will_paginate @list_email_campaign, renderer: BootstrapPagination::Rails %></div>
  </div>
</div>