config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: {
      sessions: 'admin/sessions',
      passwords: 'admin/passwords'
  }
  devise_for :users, path: 'user', controllers: { sessions: 'user/sessions',
                                                            passwords: 'user/passwords',
                                                            registrations: 'user/registrations'
                                                          }
  namespace :user, url: '/' do
    get '/search', to: 'search_email#index'
    get '/welcome', to: 'search_email#welcome_email'
    get '/searching_history', to: 'history_search_emails#index'
    get '/download-file', to: 'search_email#download'
    resources :email_campaigns, only: [:new, :create, :show, :index ]
    root to: 'search_email#index'
  end
  namespace :admin, url: '/admin' do
    resources :user, only: [:index, :destroy, :update]
    get '/edit_profile', to: "admin#edit_profile"
    post '/edit_profile', to: "admin#update_info"
    root to: 'user#index'
  end
  root to: 'user/search_email#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookie.rb
class Cookie < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/email_campaign.rb
class EmailCampaign < ApplicationRecord
  has_many :messages, class_name: "Ahoy::Message" , :foreign_key => :campaign_id
  belongs_to :user


  mount_uploader :file, EmailFileUploader

  def read_csv
    array = []
    CSV.foreach("#{Rails.public_path}/#{self.file.url}" , headers: false).each_with_index do |row, index|
      next if index == 0
      is_real = EmailValidator.valid?(row[1])
      array << row[1] if is_real
    end
    update(list_email: array)
    array
  end
end

app/models/history_search_email.rb
class HistorySearchEmail < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :email_campaigns
  has_many :history_search_emails
  has_many :messages, class_name: "Ahoy::Message"

  %w(first_name last_name).each do |i|
    validates_presence_of i
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < Admin::BaseController

  def edit_profile
    @admin = current_admin
  end

  def update_info
    @admin = current_admin
    if @admin.valid_password? params[:admin][:current_password]
      if @admin.update(user_params)
        # Sign in the user by passing validation in case their password changed
        redirect_to '/admin'
      else
        render "edit_profile"
      end
    else
      @admin.errors.add(:current_password, "is wrong")
      render "edit_profile"
    end
  end

  private

  def user_params
    params.require(:admin).permit(:password, :password_confirmation, :first_name, :last_name, :phone, :birthday, :address)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin!
  layout 'application_admin'
end

app/controllers/admin/user_controller.rb
class Admin::UserController < Admin::BaseController
  before_action :admin_set_user, only: [:delete, :update]

  def index
    @users = User.all
  end
  def destroy
    @user.delete
    redirect_to admin_index_path
  end
  def update
    is_lock = @user.is_lock
    @user.update(is_lock: !is_lock)
    redirect_to admin_index_path
  end

  def edit
    @admin = current_admin
  end

  private

  def admin_set_user
    @user = User.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin_set_user, only: [:delete, :update]

  def index
    @users = User.all
  end
  def destroy
    @user.delete
    redirect_to admin_index_path
  end
  def update
    is_lock = @user.is_lock
    @user.update(is_lock: !is_lock)
    redirect_to admin_index_path
  end

  private

  def admin_set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/email_campaigns_controller.rb
class EmailCampaignsController < ApplicationController

  def index
    @email_campaigns = EmailCampaign.where(user_id: current_user.id)
  end

  def show
    @email_campaign = EmailCampaign.find(params[:id])
    @max_number = JSON.parse(@email_campaign.list_email).length || 100
    @open_count = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").group_by_day(:opened_at, range: 2.weeks.ago..(Time.now + 2.weeks))
    @percent_complete = @email_campaign.messages.where("ahoy_messages.opened_at IS NOT NULL").count * 100/@max_number
  end

  def new
    @email_campaign = EmailCampaign.new
  end

  def create
    start_time = params[:start_time]
    end_time = params[:end_time]
    @start_time = Time.new start_time["date(1i)"].to_i, start_time["date(2i)"].to_i, start_time["date(3i)"].to_i, start_time["date(4i)"].to_i, start_time["date(5i)"].to_i
    @end_time = Time.new end_time["date(1i)"].to_i, end_time["date(2i)"].to_i, end_time["date(3i)"].to_i, end_time["date(4i)"].to_i, end_time["date(5i)"].to_i
    @email_campaign = EmailCampaign.new(start_time: @start_time, end_time: @end_time, user_id: current_user.id, file: params[:file_data])
    if @email_campaign.save!
      array = @email_campaign.read_csv
      if Rails.env = "production"
        EmailCampaignJob.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      end
      if Rails.env = "development"
        EmailCampaignWorker.perform_async(array, params[:from], params[:subject], params[:content], @email_campaign.id)
      end
      redirect_to email_campaigns_path
    else
      render 'new'
    end
  end

  private

  def send_email_params
    params.permit(:from, :content, :subject, start_time: [], end_time: [], file_data: [])
  end

end

app/controllers/history_search_emails_controller.rb
class HistorySearchEmailsController < ApplicationController
  def index
    @history_search_results = HistorySearchEmail.where(user_id: current_user.id)
  end
end

app/controllers/search_email_controller.rb
class SearchEmailController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    if params[:email]
      @search = true
      begin
        if EmailValidator.valid?(email_params)
          is_real = EmailVerifier.check(email_params)
          @email_live = is_real ? 1 : 0
        else
          @email_live = 0
        end
      rescue Exception
        @email_live = 0
      end
    else
      @search = false
    end
    respond_to do |format|
      format.html
      format.json do
        return render json: {email_is_exist: @email_live },head: 200 if @search
        render json:{email_is_exist: 0},head: 200 if !@search
      end
    end
  end

  private

  def email_params
    params.require(:email)
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user
  layout 'application_user'

  private

  def check_user
    if !current_user.nil? && current_user.is_lock && current_user.class.to_s == "User"
      sign_out current_user
      render 'layouts/lock'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name_of_user user
    if user.first_name && user.last_name
      full_name = user.first_name + " " + user.last_name
    else
      full_name = "Anonymous"
    end
    full_name
  end
end

app/helpers/history_search_emails_helper.rb
module HistorySearchEmailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_email_helper.rb
module SearchEmailHelper
end

app/views/admin/admin/edit_profile.html.erb
<div class="panel-heading">
  <h4>Edit Profile of Admin</h4>
</div>
<%= form_with scope: :admin, url: '/admin/edit_profile', method: :post, local: true do |form| %>
    <% if @admin.errors.any? %>
        <div class="alert alert-danger alert-block devise-bs">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <% @admin.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </div>
    <% end %>
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :birthday %>
      <%= form.text_field :birthday, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :phone %>
      <%= form.text_field :phone, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= form.label :password %> <i>(<%= t('.leave_blank_if_you_don_t_want_to_change_it', default: "leave blank if you don't want to change it") %>)</i>
      <%= form.password_field :password, autocomplete: "off", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= form.label :current_password %> <i>(<%= t('.we_need_your_current_password_to_confirm_your_changes', default: 'we need your current password to confirm your changes') %>)</i>
      <%= form.password_field :current_password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/admin/admin/index.html.erb
<div class="container-fluid">
  <div class="row">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Name</th>
        <th class="text-center">Email</th>
      </tr>
      </thead>
      <tbody>
      <% unless @users.nil? %>
          <% @users.each_with_index do |user, index| %>
              <tr>
                <td class="text-center"><%= index + 1 %></td>
                <td class="text-center"><%= user.first_name + user.last_name %></td>
                <td class="text-center"><%= user.email %></td>
                <% unless user.is_lock %>
                <td><%= link_to 'Lock Account', admin_admin_path(user), method: :put,
                                data: { confirm: 'Are you sure?' } %></td>
                <% else %>
                <td><%= link_to 'Unlock Account', admin_admin_path(user), method: :put,
                                data: { confirm: 'Are you sure?' } %></td>
                <% end %>
                <td><%= link_to 'Delete User', admin_admin_path(user), method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
      <% else %>
          <tr><p>No result found</p></tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/index.html.erb
<div class="container-fluid">
  <div class="row">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Name</th>
        <th class="text-center">Email</th>
      </tr>
      </thead>
      <tbody>
      <% unless @users.nil? %>
          <% @users.each_with_index do |user, index| %>
              <tr>
                <td class="text-center"><%= index + 1 %></td>
                <td class="text-center"><%= user.first_name + user.last_name %></td>
                <td class="text-center"><%= user.email %></td>
                <% unless user.is_lock %>
                <td><%= link_to 'Lock Account', admin_path(user), method: :put,
                                data: { confirm: 'Are you sure?' } %></td>
                <% else %>
                <td><%= link_to 'Unlock Account', admin_path(user), method: :put,
                                data: { confirm: 'Are you sure?' } %></td>
                <% end %>
                <td><%= link_to 'Delete User', admin_path(user), method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
      <% else %>
          <tr><p>No result found</p></tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "AceEmailHarvest" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>
<%= render 'navigation/admin_nav' %>
<main class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->
</main> <!-- /container -->
<footer>
  <div class="container">
    <p align="center">&copy; ACE_EMAIL_HARVEST TEAM 2017</p>
  </div>
</footer> <!-- /container -->
</body>
</html>

app/views/layouts/application_user.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "AceEmailHarvest" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>
<%= render 'navigation/nav' %>
<main class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->
</main> <!-- /container -->
<footer>
  <div class="container">
    <p align="center">&copy; ACE_EMAIL_HARVEST TEAM 2017</p>
  </div>
</footer> <!-- /container -->
</body>
</html>

app/views/layouts/lock.html.erb
<h1>Your account was lock! Please contact this phone number: 01202397340 for unlocking account</h1>

app/views/navigation/_admin_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/admin">AceEmailHarvest</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if current_admin %>
            <li><%= link_to "Manage user", admin_user_index_path  %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_admin %>
            <li class="dropdown">
              <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                <%= full_name_of_user(current_admin) %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a href="<%= admin_edit_profile_path %>"  class="dropdown-item"><i class="glyphicon glyphicon-user"></i> Edit Profile</a></li>
                <li><a href="<%= destroy_admin_session_path %>" data-method="delete"  class="dropdown-item"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to('Sign In', new_admin_session_path, class: 'btn btn-primary', title: 'Sign In') %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/navigation/_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">AceEmailHarvest</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Search", user_search_path %></li>
        <% if current_user && !current_user.is_lock %>
            <li><%= link_to "Searching History", user_searching_history_path  %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">
                Email Campaign
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a href="<%= new_user_email_campaign_path %>"  class="dropdown-item"><i class="glyphicon glyphicon-envelope"></i> New Email Campaign</a></li>
                <li><a href="<%= user_email_campaigns_path  %>"  class="dropdown-item"><i class="glyphicon glyphicon-list-alt"></i> History Of Email Campaigns</a></li>
              </ul>
            </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user && !current_user.is_lock %>
            <li class="dropdown">
              <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                <%= full_name_of_user(current_user) %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a href="<%= edit_user_registration_path %>"  class="dropdown-item"><i class="glyphicon glyphicon-user"></i> Edit Profile</a></li>
                <li><a href="<%= destroy_user_session_path %>" data-method="delete"  class="dropdown-item"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
            </li>
            <li>
              <%= link_to('Sign Up', new_user_registration_path , class: 'btn btn-danger', title: 'Sign Up') %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>